version: "2.3"
services:
  db:
    image: postgres:11.5-alpine
    container_name: "selene-bananas-db"
    env_file: ./.env
    ports:
      - "54320:5432" # port 5432 on container maps to 54320 on the docker host
    healthcheck:
      test: ["CMD", "pg_isready"]
      timeout: 1s
      interval: 1s
      retries: 3
      start_period: 5s
  web:
    build: .
    container_name: "selene-bananas-web"
    env_file: ./.env
    ports:
      - "${HTTPS_PORT}:8000" # port 8000 on container maps to HTTPS_PORT on docker host
      - "${HTTP_PORT}:8001"  # port 8001 on container maps to HTTP_PORT on docker host
    environment:
      - HTTPS_PORT=8000
      - HTTP_PORT=8001
      - DATABASE_URL=${DATABASE_URL_DOCKER}
    volumes:
      - ${PWD}/${TLS_CERT_FILE}:/app/${TLS_CERT_FILE}
      - ${PWD}/${TLS_KEY_FILE}:/app/${TLS_KEY_FILE}
    depends_on:
      db:
        condition: service_healthy