version: "2"
services:
  db:
    image: postgres:11.5-alpine
    container_name: "selene-bananas-db"
    env_file: ./.env
    ports:
      - "${POSTGRES_PORT}:5432" # port 5432 on container maps to POSTGRES_PORT on the docker host
    volumes:
      - ./.pgdata:/var/lib/postgresql/data # save data to local .pgdata directory
  web:
    build: .
    container_name: "selene-bananas-web"
    env_file: ./.env
    ports:
      - "${SERVER_PORT}:8000" # port 8000 on container maps to SERVER_PORT on docker host
    environment:
      - PORT=8000
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}?sslmode=disable
    depends_on:
      - db