services:
  postgres-db:
    image: postgres:15-alpine3.21
    container_name: "selene-bananas-db-postgres"
    env_file: ./.env
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGPORT=${POSTGRES_PORT}
      - PGDATABASE=${POSTGRES_DB}
  mongo-db:
    image: mongo:5.0.12
    container_name: "selene-bananas-db-mongo"
    ports:
      - "27017:27017"
  web:
    build: .
    container_name: "selene-bananas-web"
    env_file: ./.env
    ports:
      - "${HTTPS_PORT}:${HTTPS_PORT}"
      - "${HTTP_PORT}:${HTTP_PORT}"
    environment:
      - HTTPS_PORT=${HTTPS_PORT}
      - HTTP_PORT=${HTTP_PORT}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
      # - DATABASE_URL=mongodb://selene-bananas-db-mongo:27017/