CREATE OR REPLACE FUNCTION user_update_password
	( IN username VARCHAR
	, IN old_password CHAR
	, IN new_password CHAR
	) RETURNS BOOLEAN
AS
$$
	WITH updated AS
		(
		UPDATE users
		AS u
		SET password = user_update_password.new_password
		WHERE u.username = user_update_password.username
			AND u.password = user_update_password.old_password
		RETURNING u.username
		)
	SELECT COUNT(*) > 0
	FROM updated
$$
LANGUAGE SQL;
